#ifndef BOSCH_CHALLENGE_VR_HPP
#define BOSCH_CHALLENGE_VR_HPP

namespace BoschChallenge {

enum VR_Gains {
    VR_K_TRC_FB_START = 1,
    VR_K_TRC_FF_START = 7,
    VR_K_YRC_STATE_START = 9,
    VR_K_YRC_PSI_START = 15,
    VR_X0_START = 16,
    VR_NOISE_MEAN_START = 22,
    VR_NOISE_STD_START = 28,
    VR_INIT_VELOCITY = 34
};

enum VR_Triggers {
    VR_SENSOR_TRIGGER_ACTIVATED_INPUT = 100,
    VR_SENSOR_TRIGGER_FINISHED_INPUT = 101,
    VR_NETWORK_SC_TRIGGER_SENT_INPUT = 102,
    VR_NETWORK_SC_TRIGGER_RECEIVED_INPUT = 103,
    VR_ESTIMATOR_TRIGGER_ACTIVATED_INPUT = 104,
    VR_ESTIMATOR_TRIGGER_FINISHED_INPUT = 105,
    VR_CONTROLLER_TRIGGER_ACTIVATED_INPUT = 106,
    VR_CONTROLLER_TRIGGER_FINISHED_INPUT = 107,
    VR_FEEDFORWARD_TRIGGER_ACTIVATED_INPUT = 108,
    VR_FEEDFORWARD_TRIGGER_FINISHED_INPUT = 109,
    VR_MERGER_TRIGGER_ACTIVATED_INPUT = 110,
    VR_MERGER_TRIGGER_FINISHED_INPUT = 111,
    VR_NETWORK_CA_TRIGGER_SENT_INPUT = 112,
    VR_NETWORK_CA_TRIGGER_RECEIVED_INPUT = 113,
    VR_ACTUATOR_TRIGGER_ACTIVATED_INPUT = 114,
    VR_ACTUATOR_TRIGGER_FINISHED_INPUT = 115
};

enum VR_Real_Inputs {
    VR_FF_REF_0_INPUT = 116,
    VR_FF_REF_1_INPUT = 117,
    VR_VELOCITY_INPUT = 118
};

enum VR_Outputs {
    VR_PHYS_STATE_START = 1000,
    VR_SENS_OUT_START = 1006,
    VR_EST_STATE_OUT_START = 1011,
    VR_FB_PSI_DOT_OUT = 1017,
    VR_FF_OUT_START = 1018,
    VR_FF_PSI_DOT_OUT = 1020,
    VR_AGG_DELTA_OUT = 1021,
    VR_ACT_OUT = 1022,
    VR_CURRENT_TIME = 1023,
    VR_CURRENT_STEP = 1024,
    VR_LOCAL_CRITICAL = 1025,
    VR_REMOTE_CRITICAL = 1026,
    VR_REAL_CRITICAL = 1027,
    VR_LOCAL_PERF = 1028,
    VR_REMOTE_PERF = 1029,
    VR_REAL_PERF = 1030,
    VR_LOCAL_AVG_PERF = 1031,
    VR_REMOTE_AVG_PERF = 1032,
    VR_REAL_AVG_PERF = 1033,
    VR_LOCAL_ERR_CNTR = 1034,
    VR_REMOTE_ERR_CNTR = 1035,
    VR_REAL_ERR_CNTR = 1036,
    VR_LOCAL_VIOLATED = 1037,
    VR_REMOTE_VIOLATED = 1038,
    VR_REAL_VIOLATED = 1039
};

} // namespace BoschChallenge

#endif // BOSCH_CHALLENGE_VR_HPP
